# Generated by Django 4.1.3 on 2023-11-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_energyaudit_user_energydevice_user_facility_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energydevice",
            name="facility",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="audit.facility",
            ),
        ),
        migrations.AlterField(
            model_name="energydevice",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
