# Generated by Django 4.1.3 on 2023-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_energydevice_facility_alter_energydevice_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energydevice",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
