# Generated by Django 4.1.3 on 2023-11-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_alter_energydevice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyaudit",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 18, 19, 4, 57, 278569, tzinfo=datetime.timezone.utc
                ),
                verbose_name=datetime.datetime(
                    2023, 11, 18, 19, 4, 57, 278556, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
