# Generated by Django 4.1.3 on 2023-11-19 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0010_alter_energyaudit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyaudit",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
