# Generated by Django 4.1.3 on 2023-11-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0011_alter_energyaudit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyaudit",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
